# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: grinry
open_collective: grinry
ko_fi: E1E72SY7Z
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.blockchain.com/btc/address/bc1q73m0qxp0a50cp535emc8eqgmk76thzeflszu4m','https://www.blockchain.com/eth/address/0x57aa72a3ebc6be745ccc81bf21db4b51dcfb5c75?view=internal']
